name: revnet3
services:
- name: revnet3-backend
  source_dir: /backend
  github:
    repo: your-username/revnet3
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "3000"
  - key: MONGODB_URI
    value: ${MONGODB_URI}
    type: SECRET
  - key: STRIPE_SECRET_KEY
    value: ${STRIPE_SECRET_KEY}
    type: SECRET
  - key: STRIPE_PUBLISHABLE_KEY
    value: ${STRIPE_PUBLISHABLE_KEY}
    type: SECRET
  - key: STRIPE_WEBHOOK_SECRET
    value: ${STRIPE_WEBHOOK_SECRET}
    type: SECRET
  - key: FRONTEND_URL
    value: ${FRONTEND_URL}
    type: SECRET
  health_check:
    http_path: /
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3

- name: revnet3-frontend
  source_dir: /
  github:
    repo: your-username/revnet3
    branch: main
  build_command: npm run build
  run_command: npx serve -s dist/revnet -l 3001
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3001
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "3001"
  routes:
  - path: /
  health_check:
    http_path: /
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3

databases:
- name: revnet3-db
  engine: MONGODB
  version: "5"
  size: db-s-1vcpu-1gb
  num_nodes: 1
